version: '3.8'
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
  auth-service:
    build: ./auth-service
    ports:
      - "4001:4001"
  user-service:
    build: ./user-service
    ports:
      - "4002:4002"
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    ports:
      - "5432:5432"